name: Frontend CI/CD

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      
permissions:
  id-token: write # required for OIDC token request
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
  
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'



